---
# meta/main.yml — linux_packages
galaxy_info:
  role_name: linux_packages
  namespace: detrandf
  author: DETRAN-DF — Infraestrutura
  description: Instalação/remoção de pacotes e grupos (package) em RHEL, Debian e Ubuntu.
  company: DETRAN-DF
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
        - "10"
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - linux
    - packages
    - dnf
    - apt
    - aap

dependencies: []
